// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using data_mojo;

#nullable disable

namespace data_mojo.migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccessoireContrat", b =>
                {
                    b.Property<int>("AccessoiresId")
                        .HasColumnType("int");

                    b.Property<int>("ContratsId")
                        .HasColumnType("int");

                    b.HasKey("AccessoiresId", "ContratsId");

                    b.HasIndex("ContratsId");

                    b.ToTable("AccessoireContrat");
                });

            modelBuilder.Entity("data_mojo.models.Accessoire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Accessoires");
                });

            modelBuilder.Entity("data_mojo.models.Amortissement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("date");

                    b.Property<int>("DureeMois")
                        .HasColumnType("int");

                    b.Property<decimal>("ValeurInit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValeurResiduelleFinale")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("VeloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VeloId");

                    b.ToTable("Amortissements");
                });

            modelBuilder.Entity("data_mojo.models.Contrat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BeneficiaireId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateFin")
                        .HasColumnType("date");

                    b.Property<decimal>("LoyerMensuelHT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("StatutContrat")
                        .HasColumnType("bit");

                    b.Property<int>("UserRhId")
                        .HasColumnType("int");

                    b.Property<int>("VeloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiaireId");

                    b.HasIndex("UserRhId");

                    b.HasIndex("VeloId");

                    b.ToTable("Contrats");
                });

            modelBuilder.Entity("data_mojo.models.Discussion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Objet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Discussions");
                });

            modelBuilder.Entity("data_mojo.models.Intervention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cout")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateIntervention")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeIntervention")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VeloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VeloId");

                    b.ToTable("Interventions");
                });

            modelBuilder.Entity("data_mojo.models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiscussionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiscussionId");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("data_mojo.models.Organisation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActif")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("data_mojo.models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hpassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActif")
                        .HasColumnType("bit");

                    b.Property<string>("LasttName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<float>("TailleCm")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("data_mojo.models.Velo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Marque")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modele")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrixAchat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Velos");
                });

            modelBuilder.Entity("AccessoireContrat", b =>
                {
                    b.HasOne("data_mojo.models.Accessoire", null)
                        .WithMany()
                        .HasForeignKey("AccessoiresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("data_mojo.models.Contrat", null)
                        .WithMany()
                        .HasForeignKey("ContratsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("data_mojo.models.Amortissement", b =>
                {
                    b.HasOne("data_mojo.models.Velo", "Velo")
                        .WithMany("Amortissements")
                        .HasForeignKey("VeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Velo");
                });

            modelBuilder.Entity("data_mojo.models.Contrat", b =>
                {
                    b.HasOne("data_mojo.models.User", "Beneficiaire")
                        .WithMany("ContratsRecus")
                        .HasForeignKey("BeneficiaireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("data_mojo.models.User", "UserRH")
                        .WithMany("ContratsGeres")
                        .HasForeignKey("UserRhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("data_mojo.models.Velo", "Velo")
                        .WithMany("Contrats")
                        .HasForeignKey("VeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beneficiaire");

                    b.Navigation("UserRH");

                    b.Navigation("Velo");
                });

            modelBuilder.Entity("data_mojo.models.Discussion", b =>
                {
                    b.HasOne("data_mojo.models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("data_mojo.models.Intervention", b =>
                {
                    b.HasOne("data_mojo.models.Velo", "Velo")
                        .WithMany("Interventions")
                        .HasForeignKey("VeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Velo");
                });

            modelBuilder.Entity("data_mojo.models.Message", b =>
                {
                    b.HasOne("data_mojo.models.Discussion", "Discussion")
                        .WithMany()
                        .HasForeignKey("DiscussionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("data_mojo.models.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Discussion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("data_mojo.models.User", b =>
                {
                    b.HasOne("data_mojo.models.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("data_mojo.models.User", b =>
                {
                    b.Navigation("ContratsGeres");

                    b.Navigation("ContratsRecus");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("data_mojo.models.Velo", b =>
                {
                    b.Navigation("Amortissements");

                    b.Navigation("Contrats");

                    b.Navigation("Interventions");
                });
#pragma warning restore 612, 618
        }
    }
}
